import { StyleSheet } from "react-native";

const styles =StyleSheet.create({
    formContext:{
        width:'100%',
        height:'100%',
        bottom:0,
        backgroundColor:'#ffffff', 
        alignItems:'center',
        borderTopLeftRadius:30,
        borderTopRightRadius:30,
        marginTop:10,
        paddingTop:15,
    },
    form:{
        width:'100%',
        height:'auto',
        marginTop:10,
        padding:10,
    },
    formLabel:{
        color:'#000000',
        fontSize:18,
        paddingLeft:20,
        fontWeight:'bold'
    },
    formInput:{
        borderRadius:10,
        backgroundColor:'#D3D3D3',
        height:40,
        margin:12,
        marginHorizontal:10,
        paddingHorizontal:10,
    },
    buttonCalculator:{
        borderRadius:20,
        alignItems:'center',
        justifyContent:'center',
        backgroundColor:'#FF0043',
        paddingTop:14,
        paddingBottom:14,
        marginLeft:12,
        marginVertical:10,
        marginHorizontal:10,
    },
    textButtonCalculator:{
        fontSize:24,
        color:'#ffffff',
        fontWeight:'bold',
    },
    textErrorMessage:{
        color:'red',
        fontSize:14,
        fontWeight:'bold',
        width:'40%',
    },
    listImcs:{  
        marginTop:150,
        marginBottom:400,
        width:'100%',        
    },
    textListImcs:{
        marginVertical:10,        
        backgroundColor:'#d3d3d3',
        width:'100%',
        padding:15,
        borderRadius:20,
        color:'darkred',
        fontSize:24,
        textAlign:'center'
    }
   
})

export default styles;